version: "2"

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        container_name: rasp4php_nginx
        ports:
            - 7777:80
            # - 5555:81
        volumes:
            - ./docker/nginx/default:/etc/nginx/conf.d/default.conf:ro
            - ./webroot:/usr/share/nginx/html
        networks:
            rasp:
            

    rasp4php7:
        build:
            context: .
            dockerfile: ./docker/rasp4php/Dockerfile
        container_name: rasp4php7
        volumes:
            - ./webroot:/usr/share/nginx/html
            - .:/code:ro
        expose:
            - 9999
        ports:
            - 9999:9999
        cap_add:
            - SYS_PTRACE
        command: ["sh", "-c", "php-fpm7.0 -D ; python rasp-cli -H 0.0.0.0 -P 9999 --debug"]
        dns:
            - 8.8.8.8
            - 114.114.114.114
        networks:
            rasp:
                ipv4_address: 172.18.0.100

    #     links: 
    #         - db
    
    db:
        image: 'postgres'
        container_name: rasp4php_db
        restart: always
        environment:
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: RASPDB
            POSTGRES_HOST_AUTH_METHOD: md5
        networks:
            rasp:
                ipv4_address: 172.18.0.101

volumes:
    webroot:

networks:
    rasp:
        ipam:
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
